name: Generate Schematic PDFs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:8.0.0
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python .github/workflows/pdf.py
      - uses: actions/upload-pages-artifact@v2

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
